In [1]:
import pandas as pd
import numpy as np
# 지수표현 제거, 소수점 첫번째 자리까지 표현
pd.options.display.float_format = '{:.5f}'.format

In [2]:
train = pd.read_csv("./data/movies_train.csv")

print(train.shape)
print(train.dtypes)
train.head(10)

(600, 12)
title              object
distributor        object
genre              object
release_time       object
time                int64
screening_rat      object
director           object
dir_prev_bfnum    float64
dir_prev_num        int64
num_staff           int64
num_actor           int64
box_off_num         int64
dtype: object

,title,distributor,genre,release_time,time,screening_rat,director,dir_prev_bfnum,dir_prev_num,num_staff,num_actor,box_off_num
0,개들의 전쟁,롯데엔터테인먼트,액션,2012-11-22,96,청소년 관람불가,조병옥,nan,0,91,2,23398
1,내부자들,(주)쇼박스,느와르,2015-11-19,130,청소년 관람불가,우민호,1161602.50000,2,387,3,7072501
2,은밀하게 위대하게,(주)쇼박스,액션,2013-06-05,123,15세 관람가,장철수,220775.25000,4,343,4,6959083
3,나는 공무원이다,(주)NEW,코미디,2012-07-12,101,전체 관람가,구자홍,23894.00000,2,20,6,217866
4,불량남녀,쇼박스(주)미디어플렉스,코미디,2010-11-04,108,15세 관람가,신근호,1.00000,1,251,2,483387
5,강철대오 : 구국의 철가방,롯데엔터테인먼트,코미디,2012-10-25,113,15세 관람가,육상효,837969.00000,2,262,4,233211
6,길위에서,백두대간,다큐멘터리,2013-05-23,104,전체 관람가,이창재,nan,0,32,5,53526
7,회사원,(주)쇼박스,액션,2012-10-11,96,청소년 관람불가,임상윤,739522.00000,3,342,2,1110523
8,"1789, 바스티유의 연인들",유니버설픽쳐스인터내셔널코리아,뮤지컬,2014-09-18,129,전체 관람가,정성복,nan,0,3,5,4778
9,청춘그루브,(주)두타연,드라마,2012-03-15,94,15세 관람가,변성현,nan,0,138,3,868

In [3]:
test = pd.read_csv("./data/movies_test.csv")

print(test.shape)
print(train.dtypes)
test.head()

(243, 11)
title              object
distributor        object
genre              object
release_time       object
time                int64
screening_rat      object
director           object
dir_prev_bfnum    float64
dir_prev_num        int64
num_staff           int64
num_actor           int64
box_off_num         int64
dtype: object

,title,distributor,genre,release_time,time,screening_rat,director,dir_prev_bfnum,dir_prev_num,num_staff,num_actor
0,용서는 없다,시네마서비스,느와르,2010-01-07,125,청소년 관람불가,김형준,300529.00000,2,304,3
1,아빠가 여자를 좋아해,(주)쇼박스,멜로/로맨스,2010-01-14,113,12세 관람가,이광재,342700.25000,4,275,3
2,하모니,CJ 엔터테인먼트,드라마,2010-01-28,115,12세 관람가,강대규,4206610.66667,3,419,7
3,의형제,(주)쇼박스,액션,2010-02-04,116,15세 관람가,장훈,691342.00000,2,408,2
4,평행 이론,CJ 엔터테인먼트,공포,2010-02-18,110,15세 관람가,권호영,31738.00000,1,380,1

In [4]:
# 개봉일을 연,월,일 컬럼에 각각 저장하고 요일(0-월 ~ 6-일)도 저장
# release_time의 타입을 datetime으로 변경
train["release_time"] = pd.to_datetime(train["release_time"], format='%Y-%m-%d', errors='raise')
train["release_time_year"] = train["release_time"].dt.year
train["release_time_month"] = train["release_time"].dt.month
train["release_time_day"] = train["release_time"].dt.day

# release_time의 타입을 datetime으로 변경
test["release_time"] = pd.to_datetime(test["release_time"], format='%Y-%m-%d', errors='raise')
test["release_time_year"] = test["release_time"].dt.year
test["release_time_month"] = test["release_time"].dt.month
test["release_time_day"] = test["release_time"].dt.day
train.head()

,title,distributor,genre,release_time,time,screening_rat,director,dir_prev_bfnum,dir_prev_num,num_staff,num_actor,box_off_num,release_time_year,release_time_month,release_time_day
0,개들의 전쟁,롯데엔터테인먼트,액션,2012-11-22,96,청소년 관람불가,조병옥,nan,0,91,2,23398,2012,11,22
1,내부자들,(주)쇼박스,느와르,2015-11-19,130,청소년 관람불가,우민호,1161602.50000,2,387,3,7072501,2015,11,19
2,은밀하게 위대하게,(주)쇼박스,액션,2013-06-05,123,15세 관람가,장철수,220775.25000,4,343,4,6959083,2013,6,5
3,나는 공무원이다,(주)NEW,코미디,2012-07-12,101,전체 관람가,구자홍,23894.00000,2,20,6,217866,2012,7,12
4,불량남녀,쇼박스(주)미디어플렉스,코미디,2010-11-04,108,15세 관람가,신근호,1.00000,1,251,2,483387,2010,11,4

In [5]:
# '장르' 컬럼에 one-hot-encoding 사용
train_dummy = pd.get_dummies(train, columns=['genre'], prefix='genre')
test_dummy = pd.get_dummies(test, columns=['genre'], prefix='genre')
train_dummy.head()

,title,distributor,release_time,time,screening_rat,director,dir_prev_bfnum,dir_prev_num,num_staff,num_actor,...,genre_느와르,genre_다큐멘터리,genre_드라마,genre_멜로/로맨스,genre_뮤지컬,genre_미스터리,genre_서스펜스,genre_애니메이션,genre_액션,genre_코미디
0,개들의 전쟁,롯데엔터테인먼트,2012-11-22,96,청소년 관람불가,조병옥,nan,0,91,2,...,0,0,0,0,0,0,0,0,1,0
1,내부자들,(주)쇼박스,2015-11-19,130,청소년 관람불가,우민호,1161602.50000,2,387,3,...,1,0,0,0,0,0,0,0,0,0
2,은밀하게 위대하게,(주)쇼박스,2013-06-05,123,15세 관람가,장철수,220775.25000,4,343,4,...,0,0,0,0,0,0,0,0,1,0
3,나는 공무원이다,(주)NEW,2012-07-12,101,전체 관람가,구자홍,23894.00000,2,20,6,...,0,0,0,0,0,0,0,0,0,1
4,불량남녀,쇼박스(주)미디어플렉스,2010-11-04,108,15세 관람가,신근호,1.00000,1,251,2,...,0,0,0,0,0,0,0,0,0,1

In [6]:
train_dummy = train_dummy.drop(["title", "director", "distributor"], axis=1)
test_dummy = test_dummy.drop(["title", "director", "distributor"], axis=1)

In [7]:
train_dummy.columns
test_dummy.columns

Index(['release_time', 'time', 'screening_rat', 'dir_prev_bfnum',
       'dir_prev_num', 'num_staff', 'num_actor', 'release_time_year',
       'release_time_month', 'release_time_day', 'genre_SF', 'genre_공포',
       'genre_느와르', 'genre_다큐멘터리', 'genre_드라마', 'genre_멜로/로맨스', 'genre_뮤지컬',
       'genre_미스터리', 'genre_서스펜스', 'genre_애니메이션', 'genre_액션', 'genre_코미디'],
      dtype='object')

In [8]:
print(train_dummy.columns)
feature_names = ["time", "dir_prev_bfnum", "release_time" "dir_prev_num",
                 "num_actor", "genre_coded", "screening_rat_coded",
                 "distributor_coded","num_staff","day_of_the_week",
                 "release_time_month"]
feature_names

Index(['release_time', 'time', 'screening_rat', 'dir_prev_bfnum',
       'dir_prev_num', 'num_staff', 'num_actor', 'box_off_num',
       'release_time_year', 'release_time_month', 'release_time_day',
       'genre_SF', 'genre_공포', 'genre_느와르', 'genre_다큐멘터리', 'genre_드라마',
       'genre_멜로/로맨스', 'genre_뮤지컬', 'genre_미스터리', 'genre_서스펜스', 'genre_애니메이션',
       'genre_액션', 'genre_코미디'],
      dtype='object')

['time',
 'dir_prev_bfnum',
 'release_timedir_prev_num',
 'num_actor',
 'genre_coded',
 'screening_rat_coded',
 'distributor_coded',
 'num_staff',
 'day_of_the_week',
 'release_time_month']

In [9]:
label = "box_off_num"

In [10]:
# 트레이닝에 사용할 피쳐들의 데이터만 추출
# X_train = train[feature_names]
# print(X_train.shape)

# X_test = test[feature_names]
# print(X_test.shape)

X_train = train_dummy
X_train = X_train.drop(["box_off_num"], axis=1)
X_test = test_dummy

print(X_train.columns)
print(X_test.columns)

# 구할 레이블
y_train = train[label]

Index(['release_time', 'time', 'screening_rat', 'dir_prev_bfnum',
       'dir_prev_num', 'num_staff', 'num_actor', 'release_time_year',
       'release_time_month', 'release_time_day', 'genre_SF', 'genre_공포',
       'genre_느와르', 'genre_다큐멘터리', 'genre_드라마', 'genre_멜로/로맨스', 'genre_뮤지컬',
       'genre_미스터리', 'genre_서스펜스', 'genre_애니메이션', 'genre_액션', 'genre_코미디'],
      dtype='object')
Index(['release_time', 'time', 'screening_rat', 'dir_prev_bfnum',
       'dir_prev_num', 'num_staff', 'num_actor', 'release_time_year',
       'release_time_month', 'release_time_day', 'genre_SF', 'genre_공포',
       'genre_느와르', 'genre_다큐멘터리', 'genre_드라마', 'genre_멜로/로맨스', 'genre_뮤지컬',
       'genre_미스터리', 'genre_서스펜스', 'genre_애니메이션', 'genre_액션', 'genre_코미디'],
      dtype='object')

In [11]:
train_dummy.head()

,release_time,time,screening_rat,dir_prev_bfnum,dir_prev_num,num_staff,num_actor,box_off_num,release_time_year,release_time_month,...,genre_느와르,genre_다큐멘터리,genre_드라마,genre_멜로/로맨스,genre_뮤지컬,genre_미스터리,genre_서스펜스,genre_애니메이션,genre_액션,genre_코미디
0,2012-11-22,96,청소년 관람불가,nan,0,91,2,23398,2012,11,...,0,0,0,0,0,0,0,0,1,0
1,2015-11-19,130,청소년 관람불가,1161602.50000,2,387,3,7072501,2015,11,...,1,0,0,0,0,0,0,0,0,0
2,2013-06-05,123,15세 관람가,220775.25000,4,343,4,6959083,2013,6,...,0,0,0,0,0,0,0,0,1,0
3,2012-07-12,101,전체 관람가,23894.00000,2,20,6,217866,2012,7,...,0,0,0,0,0,0,0,0,0,1
4,2010-11-04,108,15세 관람가,1.00000,1,251,2,483387,2010,11,...,0,0,0,0,0,0,0,0,0,1

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

NameError: name 'X' is not defined

In [15]:
import numpy as np
from sklearn.metrics import make_scorer

def rmse(predict, actual):
    predict = np.array(predict)
    actual = np.array(actual)

    distance = predict - actual
    square_distance = distance ** 2
    mean_square_distance = square_distance.mean()
    score = np.sqrt(mean_square_distance)
    
    return score

rmse_score = make_scorer(rmse)
rmse_score

make_scorer(rmse)

In [16]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=300,
                              n_jobs=-1,
                              random_state=46)

In [17]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

n_estimators = 300

# 랜덤 서치 횟수
num_epoch = 100

# hyperparameter 탐색 결과가 저장될 리스트
coarse_hyperparameters_list = []

for epoch in range(num_epoch):
    # max depth의 값을 2~100으로 설정
    max_depth = np.random.randint(low=2, high=100)

    # 적용할 feature의 비율을 0.1~1.0로 설정
    max_features = np.random.uniform(low=0.1, high=1.0)

    model = RandomForestRegressor(n_estimators=n_estimators,
                                  max_depth=max_depth,
                                  max_features=max_features,
                                  n_jobs=-1,
                                  random_state=37)

    # cross_val_score를 실행하여 rmse의 평균 계산
    # cv는 데이터 조각 개수
    score = cross_val_score(model, X_train, y_train, cv=20, scoring=rmse_score).mean()
    
    # hyperparameter 탐색 결과를 저장할 딕셔너리
    hyperparameters = {
        'epoch': epoch,
        'score': score,
        'n_estimators': n_estimators,
        'max_depth': max_depth,
        'max_features': max_features,
    }

    # hyperparameter 탐색 결과 저장
    coarse_hyperparameters_list.append(hyperparameters)

    # hyperparameter 탐색 결과를 출력
    print(f"{epoch:2} n_estimators = {n_estimators}, max_depth = {max_depth:2}, max_features = {max_features:.6f}, Score = {score:.5f}")

# coarse_hyperparameters_list를 DataFrame으로 변환
coarse_hyperparameters_list = pd.DataFrame.from_dict(coarse_hyperparameters_list)

# coarse_hyperparameters_list를 score가 낮은 순으로 정렬
coarse_hyperparameters_list = coarse_hyperparameters_list.sort_values(by="score")

print(coarse_hyperparameters_list.shape)

# coarse_hyperparameters_list의 상위 10개 출력
coarse_hyperparameters_list.head(10)

/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 303, in fit
    X, y = self._validate_data(X, y, multi_output=True,
  File "/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/base.py", line 432, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/utils/validation.py", line 796, in check_X_y
    X = check_array(X, accept_sparse=accept_sparse,
  File "/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/utils/validation.py", line 534, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
  File "<__array_function__ internals>", line 5, in result_type
TypeError: invalid type promotion

  warnings.warn("Estimator fit failed. The score on this train-test"

 0 n_estimators = 300, max_depth = 50, max_features = 0.371119, Score = nan
 1 n_estimators = 300, max_depth = 30, max_features = 0.174209, Score = nan
 2 n_estimators = 300, max_depth = 43, max_features = 0.309068, Score = nan
 3 n_estimators = 300, max_depth = 90, max_features = 0.336789, Score = nan
 4 n_estimators = 300, max_depth = 39, max_features = 0.657883, Score = nan
 5 n_estimators = 300, max_depth = 32, max_features = 0.830650, Score = nan
 6 n_estimators = 300, max_depth = 29, max_features = 0.138072, Score = nan
 7 n_estimators = 300, max_depth = 76, max_features = 0.406130, Score = nan
 8 n_estimators = 300, max_depth = 21, max_features = 0.185889, Score = nan
 9 n_estimators = 300, max_depth = 56, max_features = 0.146344, Score = nan
10 n_estimators = 300, max_depth =  3, max_features = 0.354955, Score = nan
11 n_estimators = 300, max_depth = 84, max_features = 0.351131, Score = nan
12 n_estimators = 300, max_depth = 45, max_features = 0.951240, Score = nan
13 n_estimators = 300, max_depth = 26, max_features = 0.927559, Score = nan
14 n_estimators = 300, max_depth = 35, max_features = 0.264325, Score = nan
15 n_estimators = 300, max_depth = 15, max_features = 0.949050, Score = nan
16 n_estimators = 300, max_depth = 22, max_features = 0.303505, Score = nan
17 n_estimators = 300, max_depth = 89, max_features = 0.714696, Score = nan
18 n_estimators = 300, max_depth = 52, max_features = 0.940866, Score = nan
19 n_estimators = 300, max_depth = 61, max_features = 0.644868, Score = nan
20 n_estimators = 300, max_depth = 41, max_features = 0.245860, Score = nan
21 n_estimators = 300, max_depth = 19, max_features = 0.482212, Score = nan
22 n_estimators = 300, max_depth = 28, max_features = 0.909427, Score = nan
23 n_estimators = 300, max_depth =  6, max_features = 0.999739, Score = nan
24 n_estimators = 300, max_depth = 28, max_features = 0.610730, Score = nan
25 n_estimators = 300, max_depth =  7, max_features = 0.613390, Score = nan
26 n_estimators = 300, max_depth = 40, max_features = 0.266237, Score = nan
27 n_estimators = 300, max_depth =  8, max_features = 0.307492, Score = nan
28 n_estimators = 300, max_depth = 27, max_features = 0.621045, Score = nan
29 n_estimators = 300, max_depth = 40, max_features = 0.625155, Score = nan
30 n_estimators = 300, max_depth = 69, max_features = 0.463625, Score = nan
31 n_estimators = 300, max_depth = 73, max_features = 0.426737, Score = nan
32 n_estimators = 300, max_depth = 79, max_features = 0.495970, Score = nan
33 n_estimators = 300, max_depth = 73, max_features = 0.570507, Score = nan
34 n_estimators = 300, max_depth = 89, max_features = 0.553050, Score = nan
35 n_estimators = 300, max_depth = 80, max_features = 0.482014, Score = nan
36 n_estimators = 300, max_depth =  3, max_features = 0.688685, Score = nan
37 n_estimators = 300, max_depth = 28, max_features = 0.522817, Score = nan
38 n_estimators = 300, max_depth = 10, max_features = 0.176033, Score = nan
39 n_estimators = 300, max_depth = 45, max_features = 0.959644, Score = nan
40 n_estimators = 300, max_depth = 73, max_features = 0.356458, Score = nan
41 n_estimators = 300, max_depth = 72, max_features = 0.352537, Score = nan
42 n_estimators = 300, max_depth = 32, max_features = 0.264094, Score = nan
43 n_estimators = 300, max_depth = 69, max_features = 0.358454, Score = nan
44 n_estimators = 300, max_depth =  2, max_features = 0.478035, Score = nan
45 n_estimators = 300, max_depth = 69, max_features = 0.826733, Score = nan
46 n_estimators = 300, max_depth =  5, max_features = 0.886611, Score = nan
47 n_estimators = 300, max_depth = 13, max_features = 0.703671, Score = nan
48 n_estimators = 300, max_depth = 14, max_features = 0.407476, Score = nan
49 n_estimators = 300, max_depth = 47, max_features = 0.242259, Score = nan
50 n_estimators = 300, max_depth =  4, max_features = 0.385696, Score = nan
51 n_estimators = 300, max_depth = 17, max_features = 0.953552, Score = nan
52 n_estimators = 300, max_depth = 34, max_features = 0.272947, Score = nan
53 n_estimators = 300, max_depth = 37, max_features = 0.813779, Score = nan
54 n_estimators = 300, max_depth = 30, max_features = 0.478579, Score = nan
55 n_estimators = 300, max_depth = 94, max_features = 0.258971, Score = nan
56 n_estimators = 300, max_depth = 53, max_features = 0.829273, Score = nan
57 n_estimators = 300, max_depth = 61, max_features = 0.588406, Score = nan
58 n_estimators = 300, max_depth = 69, max_features = 0.670590, Score = nan
59 n_estimators = 300, max_depth = 55, max_features = 0.940090, Score = nan
60 n_estimators = 300, max_depth = 12, max_features = 0.564368, Score = nan
61 n_estimators = 300, max_depth = 48, max_features = 0.322760, Score = nan
62 n_estimators = 300, max_depth = 73, max_features = 0.357926, Score = nan
63 n_estimators = 300, max_depth = 75, max_features = 0.973540, Score = nan
64 n_estimators = 300, max_depth = 63, max_features = 0.835985, Score = nan
65 n_estimators = 300, max_depth = 85, max_features = 0.754652, Score = nan
66 n_estimators = 300, max_depth = 16, max_features = 0.389830, Score = nan
67 n_estimators = 300, max_depth = 81, max_features = 0.956595, Score = nan
68 n_estimators = 300, max_depth = 43, max_features = 0.207458, Score = nan
69 n_estimators = 300, max_depth = 65, max_features = 0.534228, Score = nan
70 n_estimators = 300, max_depth = 41, max_features = 0.874878, Score = nan
71 n_estimators = 300, max_depth = 81, max_features = 0.496599, Score = nan
72 n_estimators = 300, max_depth = 57, max_features = 0.551101, Score = nan
73 n_estimators = 300, max_depth = 79, max_features = 0.389560, Score = nan
74 n_estimators = 300, max_depth = 81, max_features = 0.492523, Score = nan
75 n_estimators = 300, max_depth = 33, max_features = 0.410430, Score = nan
76 n_estimators = 300, max_depth = 66, max_features = 0.577945, Score = nan
77 n_estimators = 300, max_depth = 88, max_features = 0.517517, Score = nan
78 n_estimators = 300, max_depth = 69, max_features = 0.318263, Score = nan
79 n_estimators = 300, max_depth = 45, max_features = 0.542752, Score = nan
80 n_estimators = 300, max_depth =  4, max_features = 0.729835, Score = nan
81 n_estimators = 300, max_depth = 33, max_features = 0.305867, Score = nan
82 n_estimators = 300, max_depth = 87, max_features = 0.202533, Score = nan
83 n_estimators = 300, max_depth = 17, max_features = 0.136877, Score = nan
84 n_estimators = 300, max_depth = 16, max_features = 0.868477, Score = nan
85 n_estimators = 300, max_depth =  3, max_features = 0.270655, Score = nan
86 n_estimators = 300, max_depth = 34, max_features = 0.904467, Score = nan
87 n_estimators = 300, max_depth = 47, max_features = 0.533852, Score = nan
88 n_estimators = 300, max_depth = 62, max_features = 0.152453, Score = nan
89 n_estimators = 300, max_depth = 91, max_features = 0.213269, Score = nan
90 n_estimators = 300, max_depth = 40, max_features = 0.509590, Score = nan
91 n_estimators = 300, max_depth = 48, max_features = 0.626236, Score = nan
92 n_estimators = 300, max_depth = 65, max_features = 0.267077, Score = nan
93 n_estimators = 300, max_depth = 83, max_features = 0.379678, Score = nan
94 n_estimators = 300, max_depth = 42, max_features = 0.998469, Score = nan
95 n_estimators = 300, max_depth = 84, max_features = 0.365273, Score = nan
96 n_estimators = 300, max_depth = 48, max_features = 0.241194, Score = nan
97 n_estimators = 300, max_depth = 47, max_features = 0.553370, Score = nan
98 n_estimators = 300, max_depth = 52, max_features = 0.188144, Score = nan
99 n_estimators = 300, max_depth = 47, max_features = 0.119664, Score = nan
(100, 5)

   epoch  score  n_estimators  max_depth  max_features
0      0    nan           300         50       0.37112
1      1    nan           300         30       0.17421
2      2    nan           300         43       0.30907
3      3    nan           300         90       0.33679
4      4    nan           300         39       0.65788
5      5    nan           300         32       0.83065
6      6    nan           300         29       0.13807
7      7    nan           300         76       0.40613
8      8    nan           300         21       0.18589
9      9    nan           300         56       0.14634

In [19]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

n_estimators = 300
num_epoch = 100
finer_hyperparameters_list = []

for epoch in range(num_epoch):
    # coarse 단계에서 찾은 뎁스와 피쳐비율 구간을 적용
    max_depth = np.random.randint(low=5, high=35)
    max_features = np.random.uniform(low=0.1, high=0.3)
    
    model = RandomForestRegressor(n_estimators=n_estimators,
                                  max_depth=max_depth,
                                  max_features=max_features,
                                  n_jobs=-1,
                                  random_state=37)

    score = cross_val_score(model, X_train, y_train, cv=20, scoring=rmse_score).mean()
    hyperparameters = {
        'epoch': epoch,
        'score': score,
        'n_estimators': n_estimators,
        'max_depth': max_depth,
        'max_features': max_features,
    }

    finer_hyperparameters_list.append(hyperparameters)
    print(f"{epoch:2} n_estimators = {n_estimators}, max_depth = {max_depth:2}, max_features = {max_features:.6f}, Score = {score:.5f}")

finer_hyperparameters_list = pd.DataFrame.from_dict(finer_hyperparameters_list)
finer_hyperparameters_list = finer_hyperparameters_list.sort_values(by="score")
print(finer_hyperparameters_list.shape)

finer_hyperparameters_list.head(10)

/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 303, in fit
    X, y = self._validate_data(X, y, multi_output=True,
  File "/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/base.py", line 432, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/utils/validation.py", line 796, in check_X_y
    X = check_array(X, accept_sparse=accept_sparse,
  File "/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/usr/local/Cellar/jupyterlab/2.1.5/libexec/lib/python3.8/site-packages/sklearn/utils/validation.py", line 534, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
  File "<__array_function__ internals>", line 5, in result_type
TypeError: invalid type promotion

  warnings.warn("Estimator fit failed. The score on this train-test"

 0 n_estimators = 300, max_depth = 25, max_features = 0.193758, Score = nan
 1 n_estimators = 300, max_depth = 34, max_features = 0.118521, Score = nan
 2 n_estimators = 300, max_depth = 16, max_features = 0.279869, Score = nan
 3 n_estimators = 300, max_depth = 19, max_features = 0.199773, Score = nan
 4 n_estimators = 300, max_depth = 16, max_features = 0.222089, Score = nan
 5 n_estimators = 300, max_depth = 17, max_features = 0.168780, Score = nan
 6 n_estimators = 300, max_depth = 26, max_features = 0.154534, Score = nan
 7 n_estimators = 300, max_depth =  5, max_features = 0.207158, Score = nan
 8 n_estimators = 300, max_depth = 12, max_features = 0.149937, Score = nan
 9 n_estimators = 300, max_depth = 26, max_features = 0.288817, Score = nan
10 n_estimators = 300, max_depth =  6, max_features = 0.111021, Score = nan
11 n_estimators = 300, max_depth = 11, max_features = 0.145352, Score = nan
12 n_estimators = 300, max_depth = 15, max_features = 0.179053, Score = nan
13 n_estimators = 300, max_depth = 26, max_features = 0.296815, Score = nan
14 n_estimators = 300, max_depth = 14, max_features = 0.137562, Score = nan
15 n_estimators = 300, max_depth = 24, max_features = 0.196856, Score = nan
16 n_estimators = 300, max_depth = 12, max_features = 0.190662, Score = nan
17 n_estimators = 300, max_depth = 18, max_features = 0.112931, Score = nan
18 n_estimators = 300, max_depth =  8, max_features = 0.251653, Score = nan
19 n_estimators = 300, max_depth = 34, max_features = 0.202888, Score = nan
20 n_estimators = 300, max_depth = 16, max_features = 0.211941, Score = nan
21 n_estimators = 300, max_depth =  8, max_features = 0.143358, Score = nan
22 n_estimators = 300, max_depth = 14, max_features = 0.205329, Score = nan
23 n_estimators = 300, max_depth = 31, max_features = 0.123537, Score = nan
24 n_estimators = 300, max_depth = 32, max_features = 0.293946, Score = nan
25 n_estimators = 300, max_depth = 10, max_features = 0.129424, Score = nan
26 n_estimators = 300, max_depth = 34, max_features = 0.180098, Score = nan
27 n_estimators = 300, max_depth = 30, max_features = 0.113288, Score = nan
28 n_estimators = 300, max_depth =  5, max_features = 0.299591, Score = nan
29 n_estimators = 300, max_depth =  5, max_features = 0.151049, Score = nan
30 n_estimators = 300, max_depth = 34, max_features = 0.103997, Score = nan
31 n_estimators = 300, max_depth = 11, max_features = 0.191308, Score = nan
32 n_estimators = 300, max_depth = 14, max_features = 0.250319, Score = nan
33 n_estimators = 300, max_depth = 15, max_features = 0.162411, Score = nan
34 n_estimators = 300, max_depth =  8, max_features = 0.133670, Score = nan
35 n_estimators = 300, max_depth = 24, max_features = 0.288414, Score = nan
36 n_estimators = 300, max_depth = 14, max_features = 0.157317, Score = nan
37 n_estimators = 300, max_depth = 11, max_features = 0.196972, Score = nan
38 n_estimators = 300, max_depth = 25, max_features = 0.153134, Score = nan
39 n_estimators = 300, max_depth = 30, max_features = 0.254351, Score = nan
40 n_estimators = 300, max_depth =  8, max_features = 0.288702, Score = nan
41 n_estimators = 300, max_depth = 24, max_features = 0.176936, Score = nan
42 n_estimators = 300, max_depth = 24, max_features = 0.186774, Score = nan
43 n_estimators = 300, max_depth = 34, max_features = 0.248103, Score = nan
44 n_estimators = 300, max_depth = 26, max_features = 0.210624, Score = nan
45 n_estimators = 300, max_depth =  9, max_features = 0.162764, Score = nan
46 n_estimators = 300, max_depth = 22, max_features = 0.105930, Score = nan
47 n_estimators = 300, max_depth = 29, max_features = 0.277451, Score = nan
48 n_estimators = 300, max_depth = 23, max_features = 0.137504, Score = nan
49 n_estimators = 300, max_depth = 34, max_features = 0.154626, Score = nan
50 n_estimators = 300, max_depth = 11, max_features = 0.156369, Score = nan
51 n_estimators = 300, max_depth = 34, max_features = 0.170956, Score = nan
52 n_estimators = 300, max_depth = 31, max_features = 0.174079, Score = nan
53 n_estimators = 300, max_depth =  9, max_features = 0.155669, Score = nan
54 n_estimators = 300, max_depth =  6, max_features = 0.211234, Score = nan
55 n_estimators = 300, max_depth = 14, max_features = 0.299815, Score = nan
56 n_estimators = 300, max_depth = 34, max_features = 0.201964, Score = nan
57 n_estimators = 300, max_depth = 31, max_features = 0.231515, Score = nan
58 n_estimators = 300, max_depth = 19, max_features = 0.237690, Score = nan
59 n_estimators = 300, max_depth = 33, max_features = 0.270993, Score = nan
60 n_estimators = 300, max_depth = 32, max_features = 0.191832, Score = nan
61 n_estimators = 300, max_depth = 19, max_features = 0.126586, Score = nan
62 n_estimators = 300, max_depth = 15, max_features = 0.221116, Score = nan
63 n_estimators = 300, max_depth = 25, max_features = 0.210786, Score = nan
64 n_estimators = 300, max_depth = 10, max_features = 0.299150, Score = nan
65 n_estimators = 300, max_depth = 21, max_features = 0.242771, Score = nan
66 n_estimators = 300, max_depth = 24, max_features = 0.227288, Score = nan
67 n_estimators = 300, max_depth = 28, max_features = 0.193783, Score = nan
68 n_estimators = 300, max_depth = 21, max_features = 0.292213, Score = nan
69 n_estimators = 300, max_depth = 26, max_features = 0.290845, Score = nan
70 n_estimators = 300, max_depth = 27, max_features = 0.293592, Score = nan
71 n_estimators = 300, max_depth = 32, max_features = 0.117197, Score = nan
72 n_estimators = 300, max_depth = 30, max_features = 0.148942, Score = nan
73 n_estimators = 300, max_depth = 23, max_features = 0.162099, Score = nan
74 n_estimators = 300, max_depth =  7, max_features = 0.178757, Score = nan
75 n_estimators = 300, max_depth = 26, max_features = 0.167665, Score = nan
76 n_estimators = 300, max_depth = 23, max_features = 0.235335, Score = nan
77 n_estimators = 300, max_depth = 29, max_features = 0.138748, Score = nan
78 n_estimators = 300, max_depth = 14, max_features = 0.132712, Score = nan
79 n_estimators = 300, max_depth = 22, max_features = 0.199710, Score = nan
80 n_estimators = 300, max_depth = 16, max_features = 0.155164, Score = nan
81 n_estimators = 300, max_depth =  8, max_features = 0.169661, Score = nan
82 n_estimators = 300, max_depth = 10, max_features = 0.180871, Score = nan
83 n_estimators = 300, max_depth =  9, max_features = 0.173587, Score = nan
84 n_estimators = 300, max_depth =  8, max_features = 0.121199, Score = nan
85 n_estimators = 300, max_depth = 28, max_features = 0.235892, Score = nan
86 n_estimators = 300, max_depth = 32, max_features = 0.236390, Score = nan
87 n_estimators = 300, max_depth =  7, max_features = 0.152529, Score = nan
88 n_estimators = 300, max_depth = 13, max_features = 0.293322, Score = nan
89 n_estimators = 300, max_depth = 20, max_features = 0.136538, Score = nan
90 n_estimators = 300, max_depth = 23, max_features = 0.112672, Score = nan
91 n_estimators = 300, max_depth = 15, max_features = 0.233882, Score = nan
92 n_estimators = 300, max_depth = 32, max_features = 0.165564, Score = nan
93 n_estimators = 300, max_depth = 31, max_features = 0.204215, Score = nan
94 n_estimators = 300, max_depth = 31, max_features = 0.249624, Score = nan
95 n_estimators = 300, max_depth =  5, max_features = 0.299382, Score = nan
96 n_estimators = 300, max_depth =  8, max_features = 0.120625, Score = nan
97 n_estimators = 300, max_depth = 20, max_features = 0.174150, Score = nan
98 n_estimators = 300, max_depth =  6, max_features = 0.254564, Score = nan
99 n_estimators = 300, max_depth = 16, max_features = 0.256683, Score = nan
(100, 5)

   epoch  score  n_estimators  max_depth  max_features
0      0    nan           300         25       0.19376
1      1    nan           300         34       0.11852
2      2    nan           300         16       0.27987
3      3    nan           300         19       0.19977
4      4    nan           300         16       0.22209
5      5    nan           300         17       0.16878
6      6    nan           300         26       0.15453
7      7    nan           300          5       0.20716
8      8    nan           300         12       0.14994
9      9    nan           300         26       0.28882

In [20]:
# 가장 정확도가 높은 하이퍼패러미터를 저장
best_hyperparameters = finer_hyperparameters_list.iloc[0]

best_max_depth = best_hyperparameters["max_depth"]
best_max_features = best_hyperparameters["max_features"]

print(f"max_depth(best) = {best_max_depth}, max_features(best) = {best_max_features:.6f}")

max_depth(best) = 25.0, max_features(best) = 0.193758

In [21]:
from sklearn.ensemble import RandomForestRegressor

best_n_estimators = 3000
model = RandomForestRegressor(n_estimators=best_n_estimators,
                              max_depth=best_max_depth,
                              max_features=best_max_features,
                              random_state=37,
                              n_jobs=-1)
model

RandomForestRegressor(max_depth=25.0, max_features=0.19375815782664124,
                      n_estimators=3000, n_jobs=-1, random_state=37)

In [22]:
model.fit(X_train, y_train)

TypeError: invalid type promotion

In [23]:
y_predicted = model.predict(X_test)
y_predicted

NotFittedError: This RandomForestRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [24]:
submission = pd.read_csv("./data/submission_.csv", engine='python')
submission.head()

FileNotFoundError: [Errno 2] No such file or directory: './data/submission_.csv'